# Generated by Django 2.1.15 on 2021-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'insurance',
            },
        ),
    ]
